title: "Intelligence Reimagined"   
author: "David P. Hummel"  
description: "Where the boundaries of artificial intelligence are explored" 

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "dhummel@eyesnorth.com"
twitter_username: "dphummel"
github_username: "dphummel"
linkedin_username: "davidphummel"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: minima
#remote_theme: jekyll/minima

#masthead: /img/IntelligenceReimagined2.jpeg

minima:
  skin: auto

# This shows an excert on the home page
show_excerpts: true

# paginate: 1

header_pages:
  - about.md
  - archive.md
 
permalink: none

google_analytics: G-C6T35B0DMK

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Posts
