title: "Intelligence Reimagined"           
author: "David P. Hummel"                          
description: "Where the Boundaries of Artificial Intelligence are Explored"         

# Email / Social media user names used by the minima theme:   
# All of these are optional and can be removed or commented out 
email: "dhummel@eyesnorth.com"
twitter_username: "dphummel"     
github_username: "dphummel"   
linkedin_username: "davidphummel"    
#facebook_username: username 
#flickr_username: username 
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Use the Minima theme for the blog - 
# I have customized the layout of this theme.
theme: minima
#minima:
  #skin: auto

# Show post excert on the home page of the blog -
# I have added "Read more" and "Listen to a discussion about this post" 
# links to the post excert.
show_excerpts: true

# Add pagination to the home page.
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num" 

# Add links to About and Archive pages to the menu bar.
header_pages:
  - about.md
  - archive.md

# I am not using permalink on the blog to access content.
permalink: none

# Use Google Analytics to track user activity.
google_analytics: G-C6T35B0DMK

# Support Really Simple Syndication (RSS) feed on the blog.
# This is the label which will be used to link to the feed.
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

# jekyll-feed: add support for an rss feed to the blog.
# jekyll-sitemap: 
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Posts
